Story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('lainnya', views.lainnya, name='lainnya'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/index.html')
def lainnya(request):
    return render(request,'main/lainnya.html')

main/templates/main/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Profil</title>
</head>
<body>
    {% include 'main/navbar.html'%}
    <div class="container-upper">
        <div class="ProfPic">
            <img src="{% static '/img/fotoCropped.jpg' %}" height="330px"; alt="Profile Picture">
        </div>
        <div class="Name">
            <h1 style="color: #EDF5E1; font-size: 3em;">Fariz Wahyuzan Dwitilas</h1>
            <br>
            <br>
            <br>
            <br>
            <h2 style="color: #EDF5E1;">Fasilkom UI 2019</h2>
            <h2 style="color: #EDF5E1;">1906399511</h2>
        </div>
        
    </div>

    <div class="container-bottom">
        <div class="Desc">
            <p>Anak kedua dari dua bersaudara, penghobi sepak bola dan 
                musik, penggemar klub FC Barcelona dan band rock-alternative
                Linkin Park. Saat ini menjadi pemain French Horn di UKM
                Orkestra Universitas Indonesia, OSUI Mahawaditra. </p>
        </div>
            <div class= "Riwayat">
                <h2>RIWAYAT PENDIDIKAN</h2>
                <br>
                <h3>2007-2013</h3>
                <h3>SDN Batan Indah</h3>
                <br>
                <h3>2013-2016</h3>
                <h3>SMPN 8 Tangerang Selatan</h3>
                <br>
                <h3>2016-2019</h3>
                <h3>SMAN 2 Tangerang Selatan</h3>
            </div>
            <div class="Instagram">
                <a href="https://www.instagram.com/farizwhyzn/" target="_blank" style="text-decoration: none; color: #5CDB95;">INSTAGRAM @FARIZWHYZN</a>
            </div>
    </div>
</body>
</html>

main/templates/main/lainnya.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <title>Lainnya</title>
</head>
<body>
    {% include 'main/navbar.html'%}

    <h1 style="text-align: center; margin-top: 2.5em;
    font-size: 2.5em; color: #EDF5E1;">Quotes of the Day</h1>

    <div class="container">
        <div class="qotd1" style="color: #EDF5E1;">“Live as if you were to die tomorrow. Learn as if you were to live forever.” - Mahatma Gandhi</div>
        <div class="qotd2" style="color: #EDF5E1;">“If you can do what you do best and be happy, you’re further along in life than most people.” - Leonardo DiCaprio</div>
        <div class="qotd3">“Don’t cry because it’s over, smile because it happened.” - Dr. Seuss</div>
        <div class="qotd4" style="color: #EDF5E1;">“If you love life, don’t waste time, for time is what life is made up of.” - Bruce Lee</div>
        <div class="qotd5" style="color: #EDF5E1;">"Don’t count the days, make the days count." - Muhammad Ali</div>
    </div>
    
</body>
</html>

main/templates/main/navbar.html
<!DOCTYPE html>
<html lang="en">
    <nav>
        <ul>
            <li><a href="{% url 'main:home'%}">Profil</a></li>
            <li><a href="{% url 'main:lainnya'%}">Lainnya</a></li>
            <li><a href="http://fariz-story1.herokuapp.com/">Story 1</a></li>
        </ul>
    </nav>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>